// Golden-fixture parity tests: the Swift port must reproduce the Python
// core's outputs (fixtures generated by tools/export_fixtures.py).

import Foundation
import XCTest
@testable import AthleticAnalysisCore

final class ParityTests: XCTestCase {
    // MARK: - Fixture loading

    struct Fixture {
        let name: String
        let kind: String
        let fps: Double
        let level: AthleteLevel
        let keypoints: PoseSequence
        let runSpeed: [Double]?
        let steps: [StepRecord]?
        let expected: [String: Any]
    }

    static func double(_ any: Any?) -> Double {
        if any == nil || any is NSNull { return .nan }
        if let n = any as? NSNumber { return n.doubleValue }
        return .nan
    }

    static func doubleArray(_ any: Any?) -> [Double] {
        guard let arr = any as? [Any] else { return [] }
        return arr.map { double($0) }
    }

    func loadFixture(_ name: String) throws -> Fixture {
        guard let url = Bundle.module.url(forResource: "Fixtures/\(name)",
                                          withExtension: "json")
            ?? Bundle.module.url(forResource: name, withExtension: "json",
                                 subdirectory: "Fixtures") else {
            XCTFail("fixture \(name) missing")
            throw NSError(domain: "fixture", code: 1)
        }
        let data = try Data(contentsOf: url)
        let obj = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        let kptsRaw = obj["keypoints"] as! [[Any]]
        let keypoints: PoseSequence = kptsRaw.map { frame in
            Pose(points: frame.map { p in
                let triple = p as! [Any]
                return Keypoint(x: Self.double(triple[0]),
                                y: Self.double(triple[1]),
                                conf: Self.double(triple[2]))
            })
        }

        var steps: [StepRecord]? = nil
        if let stepDicts = obj["steps"] as? [[String: Any]] {
            steps = stepDicts.map { Self.stepRecord($0) }
        }

        return Fixture(
            name: name,
            kind: obj["kind"] as! String,
            fps: Self.double(obj["fps"]),
            level: AthleteLevel(rawValue: obj["level"] as! String)!,
            keypoints: keypoints,
            runSpeed: obj["run_speed"].map { Self.doubleArray($0) },
            steps: steps,
            expected: obj["expected"] as! [String: Any])
    }

    static func stepRecord(_ d: [String: Any]) -> StepRecord {
        StepRecord(
            side: (d["side"] as! String) == "left" ? .left : .right,
            strikeFrame: Int(double(d["strike_frame"])),
            toeoffFrame: d["toeoff_frame"] is NSNull || d["toeoff_frame"] == nil
                ? nil : Int(double(d["toeoff_frame"])),
            contactTimeS: double(d["contact_time_s"]),
            flightTimeS: double(d["flight_time_s"]),
            stepTimeS: double(d["step_time_s"]),
            stepLength: double(d["step_length"]),
            stepSpeed: double(d["step_speed"]),
            kneeAngleAtStrike: double(d["knee_angle_at_strike"]),
            swingThighAngle: double(d["swing_thigh_angle"]),
            trunkLeanAtStrike: double(d["trunk_lean_at_strike"]))
    }

    // MARK: - Comparison helpers

    func assertClose(_ actual: Double, _ expected: Double, tol: Double,
                     _ label: String, file: StaticString = #filePath,
                     line: UInt = #line) {
        if expected.isNaN {
            XCTAssertTrue(actual.isNaN, "\(label): expected NaN, got \(actual)",
                          file: file, line: line)
        } else {
            XCTAssertFalse(actual.isNaN, "\(label): expected \(expected), got NaN",
                           file: file, line: line)
            XCTAssertEqual(actual, expected, accuracy: tol, label,
                           file: file, line: line)
        }
    }

    func assertSeriesClose(_ actual: [Double], _ expected: [Double],
                           tol: Double, _ label: String) {
        XCTAssertEqual(actual.count, expected.count, "\(label) length")
        for i in 0..<min(actual.count, expected.count) {
            assertClose(actual[i], expected[i], tol: tol, "\(label)[\(i)]")
        }
    }

    func checkFindings(_ findings: [FormFinding], _ expected: [[String: Any]],
                       valueTol: Double) {
        XCTAssertEqual(findings.count, expected.count, "finding count")
        for (f, e) in zip(findings, expected) {
            XCTAssertEqual(f.key, e["key"] as! String)
            XCTAssertEqual(f.phase, e["phase"] as! String, f.key)
            XCTAssertEqual(f.severity.rawValue, e["severity"] as! String, f.key)
            XCTAssertEqual(f.deviation, e["deviation"] as! String, f.key)
            assertClose(f.value, Self.double(e["value"]), tol: valueTol,
                        "\(f.key) value")
            let diagTitle = Diagnostics.diagnose(f)?.title
            let expectedTitle = e["diagnosis_title"] is NSNull
                ? nil : e["diagnosis_title"] as? String
            XCTAssertEqual(diagTitle, expectedTitle, "\(f.key) diagnosis")
        }
    }

    func checkRadar(_ radar: SprintRadar?, _ expected: Any?, tol: Double) {
        guard let exp = expected as? [String: Any] else {
            XCTAssertNil(radar)
            return
        }
        guard let radar else {
            XCTFail("expected radar, got nil")
            return
        }
        let expAxes = exp["axes"] as! [[String: Any]]
        XCTAssertEqual(radar.axes.count, expAxes.count)
        for (a, e) in zip(radar.axes, expAxes) {
            XCTAssertEqual(a.name, e["name"] as! String)
            assertClose(a.score, Self.double(e["score"]), tol: tol,
                        "\(a.name) score")
            XCTAssertEqual(a.nSteps, Int(Self.double(e["n_steps"])), a.name)
        }
        assertClose(radar.overall, Self.double(exp["overall"]), tol: tol,
                    "overall")
    }

    // MARK: - Module fixtures (coaching/diagnostics/radar tables)

    func runModuleFixture(_ name: String) throws {
        let fx = try loadFixture(name)
        var metrics = SprintMetrics()
        metrics.steps = fx.steps!
        let findings = Coaching.analyzeSprintForm(fx.keypoints, sprint: metrics,
                                                  runSpeed: fx.runSpeed,
                                                  fps: fx.fps, level: fx.level)
        checkFindings(findings, fx.expected["findings"] as! [[String: Any]],
                      valueTol: 1e-6)
        let radar = Radar.computeSprintRadar(fx.keypoints, sprint: metrics,
                                             runSpeed: fx.runSpeed,
                                             fps: fx.fps, level: fx.level)
        checkRadar(radar, fx.expected["radar"], tol: 1e-6)
    }

    func testModuleGoodForm() throws { try runModuleFixture("module_good_form") }
    func testModuleTrunkFault() throws { try runModuleFixture("module_trunk_fault") }
    func testModuleLongContact() throws { try runModuleFixture("module_long_contact") }
    func testModuleOverstride() throws { try runModuleFixture("module_overstride") }
    func testModuleContactElite() throws { try runModuleFixture("module_contact_elite") }
    func testModuleContactDev() throws { try runModuleFixture("module_contact_dev") }
    func testModuleAsymmetric() throws { try runModuleFixture("module_asymmetric") }
    func testModuleDriveOnly() throws { try runModuleFixture("module_drive_only") }

    // MARK: - Full pipeline fixture

    func testPipelineGait() throws {
        let fx = try loadFixture("pipeline_gait")
        let analysis = SprintAnalysis.analyze(rawKeypoints: fx.keypoints,
                                              fps: fx.fps, level: fx.level)

        // Angles: every series, every frame.
        let expAngles = fx.expected["angles"] as! [String: Any]
        XCTAssertEqual(Set(analysis.angles.keys), Set(expAngles.keys))
        for (key, series) in expAngles {
            assertSeriesClose(analysis.angles[key]!, Self.doubleArray(series),
                              tol: 0.05, "angles.\(key)")
        }

        // Run speed.
        assertSeriesClose(analysis.velocities.runSpeed,
                          Self.doubleArray(fx.expected["run_speed"]),
                          tol: 1e-4, "run_speed")
        XCTAssertEqual(analysis.velocities.unit,
                       fx.expected["velocity_unit"] as! String)

        // Events: exact frames/sides/kinds in order.
        let expEvents = fx.expected["events"] as! [[String: Any]]
        XCTAssertEqual(analysis.gaitEvents.count, expEvents.count, "event count")
        for (ev, e) in zip(analysis.gaitEvents, expEvents) {
            XCTAssertEqual(ev.frame, Int(Self.double(e["frame"])))
            XCTAssertEqual(ev.side.rawValue, e["side"] as! String,
                           "frame \(ev.frame)")
            XCTAssertEqual(ev.kind.rawValue, e["kind"] as! String,
                           "frame \(ev.frame)")
        }

        // Step records.
        let expSteps = (fx.expected["step_records"] as! [[String: Any]])
            .map { Self.stepRecord($0) }
        XCTAssertEqual(analysis.metrics.steps.count, expSteps.count, "step count")
        for (s, e) in zip(analysis.metrics.steps, expSteps) {
            XCTAssertEqual(s.side, e.side)
            XCTAssertEqual(s.strikeFrame, e.strikeFrame)
            XCTAssertEqual(s.toeoffFrame, e.toeoffFrame)
            assertClose(s.contactTimeS, e.contactTimeS, tol: 1e-9, "contact")
            assertClose(s.flightTimeS, e.flightTimeS, tol: 1e-9, "flight")
            assertClose(s.stepTimeS, e.stepTimeS, tol: 1e-9, "stepTime")
            assertClose(s.stepLength, e.stepLength, tol: 1e-4, "stepLength")
            assertClose(s.stepSpeed, e.stepSpeed, tol: 1e-3, "stepSpeed")
            assertClose(s.kneeAngleAtStrike, e.kneeAngleAtStrike, tol: 0.05, "knee")
            assertClose(s.swingThighAngle, e.swingThighAngle, tol: 0.05, "thigh")
            assertClose(s.trunkLeanAtStrike, e.trunkLeanAtStrike, tol: 0.05, "trunk")
        }

        // Summary metrics.
        let sum = fx.expected["summary"] as! [String: Any]
        assertClose(analysis.metrics.cadenceSpm, Self.double(sum["cadence_spm"]),
                    tol: 1e-3, "cadence")
        assertClose(analysis.metrics.meanContactS,
                    Self.double(sum["mean_contact_s"]), tol: 1e-9, "meanContact")
        assertClose(analysis.metrics.meanFlightS,
                    Self.double(sum["mean_flight_s"]), tol: 1e-9, "meanFlight")
        assertClose(analysis.metrics.meanStepLength,
                    Self.double(sum["mean_step_length"]), tol: 1e-4, "meanStepLen")
        assertClose(analysis.metrics.meanSpeed, Self.double(sum["mean_speed"]),
                    tol: 1e-3, "meanSpeed")
        assertClose(analysis.metrics.maxSpeed, Self.double(sum["max_speed"]),
                    tol: 1e-3, "maxSpeed")
        assertClose(analysis.metrics.meanTrunkLeanDeg,
                    Self.double(sum["mean_trunk_lean_deg"]), tol: 0.05, "meanTrunk")
        XCTAssertEqual(analysis.metrics.lengthUnit,
                       sum["length_unit"] as! String)
        assertClose(analysis.metrics.bodyHeightPx,
                    Self.double(sum["body_height_px"]), tol: 0.05, "bodyHeight")

        // Findings + radar (looser: accumulated smoothing differences).
        checkFindings(analysis.findings,
                      fx.expected["findings"] as! [[String: Any]],
                      valueTol: 0.05)
        checkRadar(analysis.radar, fx.expected["radar"], tol: 0.05)
    }
}
